---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ytdl-material
  namespace: default
spec:
  interval: 5m0s
  chart:
    spec:
      # renovate: registryUrl=https://tzahi12345.github.io/YoutubeDL-Material/chart/
      chart: youtubedl-material
      version: 0.0.1
      sourceRef:
        kind: HelmRepository
        name: youtubedl-material
        namespace: flux-system
  values:
    image:
      pullPolicy: IfNotPresent
    env:
      TZ: Australia/Perth

      #    persistence:
      #config:
      #  enabled: true
      #  emptyDir:
      #    enabled: false
      #  existingClaim: heimdall-config

    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: "nginx"
      hosts:
      - host: "ytdl-material.${SECRET_DOMAIN}"
        paths:
        - path: /
          pathType: Prefix
      tls:
      - hosts:
        - "ytdl-material.${SECRET_DOMAIN}"

