---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ytdl-material
  namespace: default
spec:
  interval: 5m0s
  chart:
    spec:
      # renovate: registryUrl=https://tzahi12345.github.io/YoutubeDL-Material/chart/
      chart: youtubedl-material
      version: 0.0.1
      sourceRef:
        kind: HelmRepository
        name: ytdl-material-charts
        namespace: flux-system
  values:
    image:
      pullPolicy: IfNotPresent
    env:
      TZ: Australia/Perth

      #    persistence:
      # config:
      #  enabled: true
      #  emptyDir:
      #    enabled: false
      #  existingClaim: heimdall-config

    ingress:
      enabled: true
      ingressClassName: "traefik"
      annotations:
        cert-manager.io/cluster-issuer: "letsencrypt-production"
        traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
      hosts:
        - host: "ytdl-material.${SECRET_DOMAIN}"
          paths:
            - path: /
              pathType: Prefix
      tls:
        - hosts:
            - "ytdl-material.${SECRET_DOMAIN}"
          secretName: "ytdl-material-${SECRET_DOMAIN//./-}-tls"
