---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: heimdall
  namespace: default
spec:
  interval: 5m0s
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: heimdall
      version: 8.0.1
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
  values:
    image:
      pullPolicy: IfNotPresent
    env:
      TZ: Australia/Perth
      PUID: 1001
      PGID: 1001

    persistence:
      config:
        enabled: true
        emptyDir:
          enabled: false
        existingClaim: heimdall-config

    ingress:
      main:
        enabled: true
        ingressClassName: "traefik"
        annotations:
          cert-manager.io/cluster-issuer: "letsencrypt-production"
          traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
        hosts:
          - host: "heimdall.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - "heimdall.${SECRET_DOMAIN}"
            secretName: "heimdall-${SECRET_DOMAIN//./-}-tls"
