---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kafka-operator
  namespace: kafka
spec:
  interval: 10m0s
  chart:
    spec:
      # renovate: registryUrl=https://strimzi.io/charts/
      chart: strimzi-kafka-operator
      version: 0.33.1
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: strimzi-charts
        namespace: flux-system

  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
