---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: z2jh-charts
  namespace: flux-system
spec:
  interval: 30m
  url: https://jupyterhub.github.io/helm-chart/
  timeout: 2m
