---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: adguard
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: adguard-home
      version: 3.3.1
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
  values:
    image:
      pullPolicy: IfNotPresent
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: "nginx"
      hosts:
      - host: "adguard.${SECRET_DOMAIN}"
        paths:
        - path: /
          pathType: Prefix
      tls:
      - hosts:
        - "adguard.${SECRET_DOMAIN}"
    persistence:
      config:
        enabled: true
        existingClaim: adguard-home-conf
        mountPath: /opt/adguardhome/conf
      data:
        enabled: true
        existingClaim: adguard-home-work
        mountPath: /opt/adguardhome/work
