---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: adguard-home
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: adguard-home
      version: 5.0.3
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
  values:
    image:
      pullPolicy: IfNotPresent
    env:
      TZ: Australia/Perth
    ingress:
      main:
        enabled: true
        annotations:
          kubernetes.io/ingress.class: "nginx"
        hosts:
          - host: "adguard.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - "adguard.${SECRET_DOMAIN}"
    service:
      dns-tcp:
        enabled: true
        annotations:
          metallb.universe.tf/allow-shared-ip: "ADGuard_DNS"
        type: LoadBalancer
        loadBalancerIP: 192.168.20.203
        ports:
          dns-tcp:
            enabled: true
            port: 53
            protocol: TCP
            targetPort: 53
            externalTrafficPolicy: Local
      dns-udp:
        enabled: true
        annotations:
          metallb.universe.tf/allow-shared-ip: "ADGuard_DNS"
        type: LoadBalancer
        loadBalancerIP: 192.168.20.203
        ports:
          dns-udp:
            enabled: true
            port: 53
            protocol: UDP
            targetPort: 53
            externalTrafficPolicy: Local
    persistence:
      config:
        enabled: true
        existingClaim: adguard-home-conf
        mountPath: /opt/adguardhome/conf
      data:
        enabled: true
        existingClaim: adguard-home-work
        mountPath: /opt/adguardhome/work
