---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: pihole
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://mojo2600.github.io/pihole-kubernetes/
      chart: pihole
      version: 2.9.4
      sourceRef:
        kind: HelmRepository
        name: mojo2600-charts
        namespace: flux-system
  values:
    image:
      pullPolicy: IfNotPresent

    env:
      TZ: Australia/Perth

    persistentVolumeClaim:
      enabled: true

    ingress:
      enabled: true
      ingressClassName: "traefik"
      annotations:
        cert-manager.io/cluster-issuer: "letsencrypt-production"
        traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
      hosts:
        - "pihole.shadowkrusha.net"
      paths:
        - path: /
          pathType: Prefix
      tls:
        - hosts:
            - "pihole.shadowkrusha.net"

    serviceWeb:
      loadBalancerIP: 192.168.20.200
      annotations:
        metallb.universe.tf/allow-shared-ip: pihole-svc

    serviceDns:
      loadBalancerIP: 192.168.20.201
      annotations:
        metallb.universe.tf/allow-shared-ip: pihole-svc
      type: LoadBalancer

    resources:
      limits:
        cpu: 200m
        memory: 256Mi
      requests:
        cpu: 100m
        memory: 128Mi
    # If using in the real world, set up admin.existingSecret instead.
    adminPassword: admin
