---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: youtubedl
  namespace: media
spec:
  interval: 5m0s
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: youtubedl-material
      version: 4.4.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
  values:
    image:
      pullPolicy: IfNotPresent
      tag: "4.3"
    env:
      TZ: Australia/Perth

    persistence:
      config:
        enabled: true
        mountPath: /app/appdata
        existingClaim: ytdl-material-claim-appdata
      audio:
        enabled: true
        mountPath: /app/audio
        existingClaim: ytdl-material-claim-audio
      subscriptions:
        enabled: true
        mountPath: /app/subscriptions
        existingClaim: ytdl-material-claim-subscriptions
      users:
        enabled: true
        mountPath: /users
        existingClaim: ytdl-material-claim-users
      video:
        enabled: true
        mountPath: /app/video
        existingClaim: ytdl-material-claim-video

    ingress:
      enabled: true
      ingressClassName: "traefik"
      annotations:
        cert-manager.io/cluster-issuer: "letsencrypt-production"
        traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
      hosts:
        - host: &host "ytdl-material.${SECRET_DOMAIN}"
          paths:
            - path: /
              pathType: Prefix
      tls:
        - hosts:
            - *host
          secretName: "ytdl-material-${SECRET_DOMAIN//./-}-tls"
