---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
  namespace: flux-system
data:
  NAS_ADDR: "192.168.86.150"
  #
  METALLB_LB_RANGE: 192.168.86.200-192.168.86.219
  INGRESS_NGINX_LB: 192.168.86.200
