---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: influxdb-config
  namespace: monitoring
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 8Gi
