---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: influxdb
  namespace: monitoring
spec:
  interval: 5m0s
  chart:
    spec:
      # renovate: registryUrl=https://helm.influxdata.com/
      chart: influxdb
      version: 4.12.1
      sourceRef:
        kind: HelmRepository
        name: influxdata-charts
        namespace: flux-system
  values:
    image:
      tag: 1.8.10
      pullPolicy: IfNotPresent

    env:
      - name: TZ
        value: Australia/Perth

    persistence:
      config:
        enabled: true
        StorageClass: nfs-csi

    ingress:
      enabled: true
      ingressClassName: "traefik"
      annotations:
        cert-manager.io/cluster-issuer: "letsencrypt-production"
        traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
      hostname: "influx.${SECRET_DOMAIN}"
      tls: true
      secretName: "influx-${SECRET_DOMAIN//./-}-tls"
