---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - dashboards
  - databases
  - default
  # - development
  - kube-system
  - media
  - monitoring
  - networking
  - system-upgrade
  - wordpress
