---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # renovate: registryUrl=https://helm.traefik.io/traefik chart=traefik
  - https://github.com/traefik/traefik-helm-chart/traefik/crds/
