---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: neo4j-database
  namespace: databases
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs-csi
  resources:
    requests:
      storage: 1Gi
