---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: neo4j
  namespace: databases
spec:
  chart:
    spec:
      chart: neo4j
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: neo4j-charts
  interval: 10m0s
  values:
    neo4j:
      acceptLicenseAgreement: "yes"
      name: my-standalone
      password: my-initial-password
      resources:
        cpu: "0.5"
        memory: 2Gi
    volumes:
      data:
        defaultStorageClass:
          requests:
            storage: 2Gi
        mode: defaultStorageClass
