---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: neo4j
  namespace: databases
spec:
  interval: 10m0s
  chart:
    spec:
      # renovate: registryUrl=https://helm.neo4j.com/neo4j
      chart: neo4j
      version: 5.4.0
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: neo4j-charts
        namespace: flux-system
  values:
    neo4j:
      name: my-standalone
      resources:
        cpu: "0.5"
        memory: "2Gi"

      # Uncomment to set the initial password
      password: "my-initial-password"

      # Uncomment to use enterprise edition
      #edition: "enterprise"
      acceptLicenseAgreement: "yes"

    volumes:
      data:
        mode: defaultStorageClass
        defaultStorageClass:
          requests:
            storage: 2Gi

  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
