---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: neo4j
  namespace: databases
spec:
  chart:
    spec:
      # renovate: registryUrl=https://helm.neo4j.com/neo4j
      chart: neo4j
      version: 5.26.12
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: neo4j-charts
        namespace: flux-system
  interval: 10m0s
  values:
    neo4j:
      acceptLicenseAgreement: "yes"
      name: my-standalone
      password: my-initial-password
      resources:
        cpu: "0.5"
        memory: 2Gi
    volumes:
      data:
        defaultStorageClass:
          requests:
            storage: 2Gi
        mode: defaultStorageClass
