---
# Source: neo4j/templates/neo4j-loadbalancer.yaml
# Service for applications that need access to neo4j
apiVersion: v1
kind: Service
metadata:
  name: "my-standalone-lb-neo4j"
  namespace: "databases"
  labels:
    helm.neo4j.com/neo4j.name: "my-standalone"
    app: "my-standalone"
    helm.neo4j.com/service: "neo4j"
  annotations:
    helm.sh/resource-policy: keep
spec:
  type: "LoadBalancer"

  externalTrafficPolicy: Local
  sessionAffinity: None
  ports:
    - protocol: TCP
      port: 7474
      targetPort: 7474
      name: http
    - protocol: TCP
      port: 7473
      targetPort: 7473
      name: https
    - protocol: TCP
      port: 7687
      targetPort: 7687
      name: tcp-bolt


  selector:
    app: "my-standalone"
    helm.neo4j.com/clustering: "false"
    helm.neo4j.com/neo4j.loadbalancer: include
