# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-token-secret
    namespace: cert-manager
stringData:
    cloudflare-token: ENC[AES256_GCM,data:/GQZCXH3IeM76j24bVbT0kT7iwGUteBcZteWgMsoe7Cv7HbscpmPnw==,iv:gSxwJGj+VCqaVeNXMvUpnx/cN4GOIhrQaHOmBZ5wRAg=,tag:T6zl6EquCoMm2looN70kCQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-04-26T04:11:26Z"
    mac: ENC[AES256_GCM,data:lBmWWw0FWqCV1hYwQgB87zAjjChW0Ehrlj8T/rAF9krL7tsKhifjGqaUSKv67NR8zRv/2VWjc59vVxnNdi/XYq2T44ovbPjI1jF/Xh7ZydFMNEAqME8U9auGseq++gxXlmBxHkGDUbpgI6CM+2e6g6ufWeB2/o0cEWJRE1dHIs8=,iv:+R56w66iPjyNpdSBh0bdPqBCWLVld5Fc+2I4PJopdJg=,tag:1QlRLIV+R6wT9p7j0EY/8A==,type:str]
    pgp:
        - created_at: "2021-04-26T04:11:24Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMAxY/RitOZC1CARAApKJKkvIfdfNSkntL303hUX8PIrK1NyWhi4ECdqwLkLcl
            3+0RO+1DWpy0HVyCQMClKPFycwbxoD1ItOM7+Hb4AAQd95d6SyhXMmcT1RabvXEf
            XeA9avXVnY1URTmM6apHrRUlFIQ2AcdTKmXTKIMlVRHJo8+sTlZ1s6aiYs98pGRd
            odDwOhwzVlSmaOEXl26lWHxCB3Jk8EdDaj+CYNmLeKxoORNRDYSnePlbh/hK+VGB
            L/ayGxHvxs5f4L4GgD7+rvwi9SkDrLDyt/xAdW+a2NGGQMiCHemsyV+Z/MTSE7IS
            r260FfXaHy5WwjZmacHEcwkrRdn9bQ3UZvjrLXv0eflLk8VeysjpgFhx2Pj0mOSk
            5IUJ3bikLd23JASzwCOGrE2rI6AY3aqsKg9uztUB4nv23cfq5MeyUrzG1LoEy28H
            Vk66zdUgfaFMwPaSRzFBeteVDo6Sg8BSy+OpPnB9rlA5OWBDe1PL0B9B3drVmxCE
            UK/oxdqvHl7Ggz58uE6XFPP0wzLzBhYr/Bt9B1lMG/68PoI/bA0ACFGcxr3nDo2u
            jM9HzRytpqC4hJTNgiFtEW86knC1CzUJqFqSNulIpCJG0YQWgqiqVchtUfK+51oQ
            uo90hVAqHV63zL8bkO+jAlB37fvi5/dKcPsgYK2tZWogqiJ/+LDLgn8Rj3rB9FvS
            XgHTIHXS7BotG3Ww49smgJSLWNX4fS41qsz7r8v0NY/EgZq1VkIjOoyFKgUXuCJ2
            B/lk4JkLYJn97jKmQpJdD11Lv4KOxs/NmzOuHEcq0wruOMZRHJiHmWoVC0RmBsk=
            =dqpd
            -----END PGP MESSAGE-----
          fp: ADAD11EB414966913B4490B24E4F42E8C97346FA
        - created_at: "2021-04-26T04:11:24Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA0s6ZAYvic26AQ//Xc6uN+CmgYTp2srPMnSB4FgOSMYqM4Rp04G8DoEXu7pU
            kv6wHXx+zcXC+dSI9MLkCFsT1D1Sg3fx2rrmfETKozxgurt9PyYW+Jdg+w+nQusP
            MXXwBVCaa2t9xut9ZCxXGFNL/5fNaSmhPjXnRX60Lu7TqqNr+MnPv6aXkoSgV9nh
            nQ0cm++d8AeFeGjGgDLENZEuJ9lv6yuiF22UitArGQ+s8bpnJEFgP3WMX+P30M54
            mq5fYIZouOJjbSR423Jhc2oWC1cdeeOQq83AYGWVnZMCsruRQdzXrQJd9+tYKPBh
            jqXEsIKx602ouudD4eklnRLpoUVDdkUx5bYsIZLboN7DtQYR6+befnXeE6YTFSN4
            svv4cwzu7sE3BgU7JUUBMnLLppw1T9zzIT86/JT3x+r7NoZck75r+YGHjLPBJPlz
            9j4q9lwfnvnv+5t9HNrSB9m2rjRng0H5aiE6jyFT7qW1sNbPU53sdetLIjowhLTp
            +JaFpBMDiNCnDBQzhCu4/U2Y5YZirtlbAWpcyrAKj+dJfrxgtbtODjgACLxa/piN
            JFhAZzhUCzDVp7BZ6POLRUC+LAQu0/zkPNXwyAj+3NWCrFqZNyCEdLWri8vRUzzk
            m+PJpvb7gTpJgVLFl/NifV0kEU0SPFoKxoCdFOkb8tH2D7ymCnt2LkIo2MtoYYrS
            XgGCH4yTismasga0iii/GkT82/KLLcHPSnVxl7L1yscC72Y7jB1G+CqEHezsoJI4
            dalu10Z4rPCIWiVkoFL1WBKvPinZPfAC8iOvyz3g5lguqw1rHWSqeMXkHjyPwMQ=
            =vyYT
            -----END PGP MESSAGE-----
          fp: 2698A4F62F6A6CF1D34C5088309BF639C751A407
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
