---
name: Lint Markdown files on Pull Requests

on: # yamllint disable-line rule:truthy
  pull_request:
    paths:
      - "**.md"

jobs:
  markdownlint:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3
      - name: Get changes
        uses: dorny/paths-filter@v2
        id: filter
        with:
          list-files: shell
          filters: |
            markdown:
              - added|modified: "**.md"
      - name: Lint files
        if: ${{ steps.filter.outputs.markdown == 'true' }}
        uses: reviewdog/action-shellcheck@f52d78284b4941028952125a10c76676c3d456eb # v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          markdownlint_flags: "-c '.github/linters/.markdownlint.yaml' ${{ steps.filter.outputs.markdown_files }}"
