---
name: Lint Shell scripts on Pull Requests

on: # yamllint disable-line rule:truthy
  pull_request:
    paths:
      - "**.sh"

jobs:
  shellcheck:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3
      - name: Get changes
        uses: dorny/paths-filter@v2
        id: filter
        with:
          list-files: shell
          filters: |
            shell:
              - added|modified: "**.sh"
      - name: Lint files
        if: ${{ steps.filter.outputs.shell == 'true' }}
        uses: reviewdog/action-shellcheck@50e5e1e2284575f23a1e409d9c0804cdfc4f6e31 # v1
        with:
          shellcheck_flags: "${{ steps.filter.outputs.shell_files }}"
