---
name: Schedule - Update Helm Release Renovate annotations

on: # yamllint disable-line rule:truthy
  workflow_dispatch:
  schedule:
    - cron: "0 */4 * * *"

jobs:
  update-helm-release-annotations:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3
      - uses: k8s-at-home/renovate-helm-releases@c465468aea461abd747f8cd72ec14031f8d1ed7b # v1
        with:
          cluster-path: "./cluster"
      - uses: peter-evans/create-pull-request@153407881ec5c347639a548ade7d8ad1d6740e38 # v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: renovate-annotations
          delete-branch: true
          title: "chore(deps): update renovate annotations"
          signoff: true
          committer: "Iain Riley <shadowkrusha@users.noreply.github.com>"
          author: "Iain Riley <shadowkrusha@users.noreply.github.com>"
          assignees: "shadowkrusha"
          commit-message: "chore(deps): update renovate annotations"
          body: |
            Update Helm Releases in order for Renovate to pick up new versions of Helm charts
          labels: renovate/annotations
